package com.rskickbox.app

fun rsLoginT94(lang:RsLang,key:String):String{
    val en=mapOf(
        "enter_email" to "Enter your email address.",
        "enter_password" to "Enter your password.",
        "checking" to "Checking your email and password…",
        "login_failed" to "Login failed. You can try again or use Forgot password.",
        "reset_email_first" to "Enter the email address for your RS KICKBOXING account first.",
        "sending_reset" to "Sending password reset email…",
        "reset_sent" to "✓ If this email belongs to an RS KICKBOXING account, a password-reset email has been sent. Open the link in that email to return to the app and choose a new password.",
        "reset_failed" to "Could not request a password reset.",
        "new_password_min" to "Choose a new password with at least 10 characters.",
        "passwords_no_match" to "The two passwords do not match.",
        "updating_password" to "Updating your password…",
        "password_updated" to "✓ Password updated. You can now sign in with your new password.",
        "password_update_failed" to "Could not update password. If you have not opened the reset link from your email yet, open that link first.",
        "activating" to "Activating your RS KICKBOXING account…",
        "account_signin_failed" to "Account created, but sign-in failed.",
        "activate_failed" to "Could not activate invitation.",
        "invite_loaded" to "Invitation loaded. Choose a password with at least 10 characters.",
        "recovery_title" to "Choose a new password",
        "forgot_title" to "Forgot your password?",
        "forgot_desc" to "Enter the email address used for your RS KICKBOXING account. We will send a secure link to create a new password.",
        "recovery_desc" to "The recovery link has returned you to RS KICKBOXING. Choose your new password below.",
        "new_password" to "New password (10+ characters)",
        "create_password" to "Create password (10+ characters)",
        "confirm_password" to "Confirm new password",
        "wait" to "Please wait…",
        "save_new_password" to "Save new password",
        "send_reset" to "Send password reset email",
        "activate_account" to "Activate account",
        "sign_in" to "Sign in",
        "forgot_button" to "Forgot password? Ask for a new one",
        "back_signin" to "Back to sign in",
        "reset_screen" to "Reset login screen",
        "cloud_connected" to "● Cloud login connected",
        "cloud_missing" to "● Cloud backend is not configured in this build",
        "login_tip" to "Wrong login details clear automatically so the form is ready for another attempt. Password recovery uses a secure email link.",
        "build_desc" to "Trainer-created accounts · secure QR invitations · password recovery · authenticated cloud sessions."
    )
    val nl=en+mapOf(
        "enter_email" to "Vul je e-mailadres in.","enter_password" to "Vul je wachtwoord in.","checking" to "E-mail en wachtwoord controleren…",
        "login_failed" to "Inloggen mislukt. Probeer opnieuw of gebruik Wachtwoord vergeten.","reset_email_first" to "Vul eerst het e-mailadres van je RS KICKBOXING-account in.",
        "sending_reset" to "E-mail voor wachtwoordherstel versturen…","reset_sent" to "✓ Als dit e-mailadres bij een RS KICKBOXING-account hoort, is een herstelmail verstuurd. Open de link in die e-mail om terug te keren naar de app en een nieuw wachtwoord te kiezen.",
        "reset_failed" to "Wachtwoordherstel kon niet worden aangevraagd.","new_password_min" to "Kies een nieuw wachtwoord van minimaal 10 tekens.","passwords_no_match" to "De twee wachtwoorden komen niet overeen.",
        "updating_password" to "Wachtwoord bijwerken…","password_updated" to "✓ Wachtwoord bijgewerkt. Je kunt nu inloggen met je nieuwe wachtwoord.","password_update_failed" to "Wachtwoord kon niet worden bijgewerkt. Open eerst de herstel-link uit je e-mail als je dat nog niet hebt gedaan.",
        "activating" to "RS KICKBOXING-account activeren…","account_signin_failed" to "Account aangemaakt, maar inloggen is mislukt.","activate_failed" to "Uitnodiging kon niet worden geactiveerd.","invite_loaded" to "Uitnodiging geladen. Kies een wachtwoord van minimaal 10 tekens.",
        "recovery_title" to "Kies een nieuw wachtwoord","forgot_title" to "Wachtwoord vergeten?","forgot_desc" to "Vul het e-mailadres van je RS KICKBOXING-account in. We sturen een beveiligde link om een nieuw wachtwoord te maken.","recovery_desc" to "De herstel-link heeft je teruggebracht naar RS KICKBOXING. Kies hieronder je nieuwe wachtwoord.",
        "new_password" to "Nieuw wachtwoord (10+ tekens)","create_password" to "Wachtwoord maken (10+ tekens)","confirm_password" to "Bevestig nieuw wachtwoord","wait" to "Even wachten…","save_new_password" to "Nieuw wachtwoord opslaan","send_reset" to "Herstelmail versturen","activate_account" to "Account activeren","sign_in" to "Inloggen","forgot_button" to "Wachtwoord vergeten? Vraag een nieuw aan","back_signin" to "Terug naar inloggen","reset_screen" to "Inlogscherm resetten",
        "cloud_connected" to "● Cloud-login verbonden","cloud_missing" to "● Cloud-backend is niet geconfigureerd in deze build","login_tip" to "Foute inloggegevens worden automatisch gewist zodat je direct opnieuw kunt proberen. Wachtwoordherstel gebruikt een beveiligde e-maillink.","build_desc" to "Accounts door trainer · beveiligde QR-uitnodigingen · wachtwoordherstel · cloudsessies."
    )
    val pt=en+mapOf(
        "enter_email" to "Introduz o teu e-mail.","enter_password" to "Introduz a tua palavra-passe.","checking" to "A verificar e-mail e palavra-passe…",
        "login_failed" to "Falha no login. Tenta novamente ou usa Esqueci a palavra-passe.","reset_email_first" to "Introduz primeiro o e-mail da tua conta RS KICKBOXING.",
        "sending_reset" to "A enviar e-mail de recuperação…","reset_sent" to "✓ Se este e-mail pertence a uma conta RS KICKBOXING, foi enviado um e-mail de recuperação. Abre o link para voltar à app e escolher uma nova palavra-passe.",
        "reset_failed" to "Não foi possível pedir a recuperação da palavra-passe.","new_password_min" to "Escolhe uma nova palavra-passe com pelo menos 10 caracteres.","passwords_no_match" to "As duas palavras-passe não coincidem.",
        "updating_password" to "A atualizar palavra-passe…","password_updated" to "✓ Palavra-passe atualizada. Já podes entrar com a nova palavra-passe.","password_update_failed" to "Não foi possível atualizar a palavra-passe. Se ainda não abriste o link de recuperação no e-mail, abre-o primeiro.",
        "activating" to "A ativar a tua conta RS KICKBOXING…","account_signin_failed" to "Conta criada, mas o login falhou.","activate_failed" to "Não foi possível ativar o convite.","invite_loaded" to "Convite carregado. Escolhe uma palavra-passe com pelo menos 10 caracteres.",
        "recovery_title" to "Escolhe uma nova palavra-passe","forgot_title" to "Esqueceste a palavra-passe?","forgot_desc" to "Introduz o e-mail usado na tua conta RS KICKBOXING. Vamos enviar um link seguro para criares uma nova palavra-passe.","recovery_desc" to "O link de recuperação trouxe-te de volta ao RS KICKBOXING. Escolhe abaixo a nova palavra-passe.",
        "new_password" to "Nova palavra-passe (10+ caracteres)","create_password" to "Criar palavra-passe (10+ caracteres)","confirm_password" to "Confirmar nova palavra-passe","wait" to "Aguarda…","save_new_password" to "Guardar nova palavra-passe","send_reset" to "Enviar e-mail de recuperação","activate_account" to "Ativar conta","sign_in" to "Entrar","forgot_button" to "Esqueceste a palavra-passe? Pede uma nova","back_signin" to "Voltar ao login","reset_screen" to "Repor ecrã de login",
        "cloud_connected" to "● Login cloud ligado","cloud_missing" to "● Backend cloud não configurado nesta versão","login_tip" to "Dados de login errados são limpos automaticamente para uma nova tentativa. A recuperação usa um link seguro por e-mail.","build_desc" to "Contas criadas pelo treinador · convites QR seguros · recuperação de palavra-passe · sessões cloud autenticadas."
    )
    val es=en+mapOf(
        "enter_email" to "Introduce tu correo.","enter_password" to "Introduce tu contraseña.","checking" to "Comprobando correo y contraseña…","login_failed" to "Error de acceso. Inténtalo de nuevo o usa Olvidé mi contraseña.","reset_email_first" to "Introduce primero el correo de tu cuenta RS KICKBOXING.","sending_reset" to "Enviando correo de recuperación…","reset_sent" to "✓ Si este correo pertenece a una cuenta RS KICKBOXING, se ha enviado un correo de recuperación. Abre el enlace para volver a la app y elegir una nueva contraseña.","reset_failed" to "No se pudo solicitar la recuperación.","new_password_min" to "Elige una contraseña nueva de al menos 10 caracteres.","passwords_no_match" to "Las dos contraseñas no coinciden.","updating_password" to "Actualizando contraseña…","password_updated" to "✓ Contraseña actualizada. Ya puedes iniciar sesión con la nueva.","password_update_failed" to "No se pudo actualizar la contraseña. Abre primero el enlace de recuperación del correo si aún no lo hiciste.","activating" to "Activando tu cuenta RS KICKBOXING…","account_signin_failed" to "Cuenta creada, pero el acceso falló.","activate_failed" to "No se pudo activar la invitación.","invite_loaded" to "Invitación cargada. Elige una contraseña de al menos 10 caracteres.","recovery_title" to "Elige una nueva contraseña","forgot_title" to "¿Olvidaste tu contraseña?","forgot_desc" to "Introduce el correo usado en tu cuenta RS KICKBOXING. Enviaremos un enlace seguro para crear una nueva contraseña.","recovery_desc" to "El enlace de recuperación te ha devuelto a RS KICKBOXING. Elige tu nueva contraseña.","new_password" to "Nueva contraseña (10+ caracteres)","create_password" to "Crear contraseña (10+ caracteres)","confirm_password" to "Confirmar nueva contraseña","wait" to "Espera…","save_new_password" to "Guardar nueva contraseña","send_reset" to "Enviar correo de recuperación","activate_account" to "Activar cuenta","sign_in" to "Iniciar sesión","forgot_button" to "¿Olvidaste la contraseña? Solicita una nueva","back_signin" to "Volver al acceso","reset_screen" to "Reiniciar pantalla de acceso","cloud_connected" to "● Acceso cloud conectado","cloud_missing" to "● Backend cloud no configurado en esta versión","login_tip" to "Los datos incorrectos se borran automáticamente para volver a intentarlo. La recuperación usa un enlace seguro por correo.","build_desc" to "Cuentas creadas por entrenador · invitaciones QR seguras · recuperación de contraseña · sesiones cloud autenticadas."
    )
    val fr=en+mapOf(
        "enter_email" to "Entre ton e-mail.","enter_password" to "Entre ton mot de passe.","checking" to "Vérification e-mail et mot de passe…","login_failed" to "Connexion échouée. Réessaie ou utilise Mot de passe oublié.","reset_email_first" to "Entre d'abord l'e-mail de ton compte RS KICKBOXING.","sending_reset" to "Envoi de l'e-mail de récupération…","reset_sent" to "✓ Si cet e-mail appartient à un compte RS KICKBOXING, un e-mail de récupération a été envoyé. Ouvre le lien pour revenir dans l'app et choisir un nouveau mot de passe.","reset_failed" to "Impossible de demander la récupération.","new_password_min" to "Choisis un nouveau mot de passe d'au moins 10 caractères.","passwords_no_match" to "Les deux mots de passe ne correspondent pas.","updating_password" to "Mise à jour du mot de passe…","password_updated" to "✓ Mot de passe mis à jour. Tu peux maintenant te connecter avec le nouveau.","password_update_failed" to "Impossible de mettre à jour le mot de passe. Ouvre d'abord le lien de récupération de l'e-mail si nécessaire.","activating" to "Activation de ton compte RS KICKBOXING…","account_signin_failed" to "Compte créé, mais la connexion a échoué.","activate_failed" to "Impossible d'activer l'invitation.","invite_loaded" to "Invitation chargée. Choisis un mot de passe d'au moins 10 caractères.","recovery_title" to "Choisis un nouveau mot de passe","forgot_title" to "Mot de passe oublié ?","forgot_desc" to "Entre l'e-mail utilisé pour ton compte RS KICKBOXING. Nous enverrons un lien sécurisé pour créer un nouveau mot de passe.","recovery_desc" to "Le lien de récupération t'a ramené dans RS KICKBOXING. Choisis ton nouveau mot de passe.","new_password" to "Nouveau mot de passe (10+ caractères)","create_password" to "Créer mot de passe (10+ caractères)","confirm_password" to "Confirmer le nouveau mot de passe","wait" to "Patiente…","save_new_password" to "Enregistrer le nouveau mot de passe","send_reset" to "Envoyer l'e-mail de récupération","activate_account" to "Activer le compte","sign_in" to "Se connecter","forgot_button" to "Mot de passe oublié ? Demander un nouveau","back_signin" to "Retour connexion","reset_screen" to "Réinitialiser l'écran de connexion","cloud_connected" to "● Connexion cloud active","cloud_missing" to "● Backend cloud non configuré dans cette version","login_tip" to "Les mauvais identifiants sont effacés automatiquement pour réessayer. La récupération utilise un lien e-mail sécurisé.","build_desc" to "Comptes créés par entraîneur · invitations QR sécurisées · récupération mot de passe · sessions cloud authentifiées."
    )
    val de=en+mapOf(
        "enter_email" to "E-Mail-Adresse eingeben.","enter_password" to "Passwort eingeben.","checking" to "E-Mail und Passwort werden geprüft…","login_failed" to "Anmeldung fehlgeschlagen. Erneut versuchen oder Passwort vergessen nutzen.","reset_email_first" to "Zuerst die E-Mail deines RS KICKBOXING-Kontos eingeben.","sending_reset" to "Passwort-Reset-E-Mail wird gesendet…","reset_sent" to "✓ Wenn diese E-Mail zu einem RS KICKBOXING-Konto gehört, wurde eine Reset-E-Mail gesendet. Öffne den Link, um zur App zurückzukehren und ein neues Passwort zu wählen.","reset_failed" to "Passwort-Reset konnte nicht angefordert werden.","new_password_min" to "Wähle ein neues Passwort mit mindestens 10 Zeichen.","passwords_no_match" to "Die beiden Passwörter stimmen nicht überein.","updating_password" to "Passwort wird aktualisiert…","password_updated" to "✓ Passwort aktualisiert. Du kannst dich jetzt mit dem neuen Passwort anmelden.","password_update_failed" to "Passwort konnte nicht aktualisiert werden. Öffne zuerst den Reset-Link aus der E-Mail.","activating" to "RS KICKBOXING-Konto wird aktiviert…","account_signin_failed" to "Konto erstellt, Anmeldung aber fehlgeschlagen.","activate_failed" to "Einladung konnte nicht aktiviert werden.","invite_loaded" to "Einladung geladen. Wähle ein Passwort mit mindestens 10 Zeichen.","recovery_title" to "Neues Passwort wählen","forgot_title" to "Passwort vergessen?","forgot_desc" to "Gib die E-Mail deines RS KICKBOXING-Kontos ein. Wir senden einen sicheren Link für ein neues Passwort.","recovery_desc" to "Der Reset-Link hat dich zu RS KICKBOXING zurückgebracht. Wähle unten dein neues Passwort.","new_password" to "Neues Passwort (10+ Zeichen)","create_password" to "Passwort erstellen (10+ Zeichen)","confirm_password" to "Neues Passwort bestätigen","wait" to "Bitte warten…","save_new_password" to "Neues Passwort speichern","send_reset" to "Reset-E-Mail senden","activate_account" to "Konto aktivieren","sign_in" to "Anmelden","forgot_button" to "Passwort vergessen? Neues anfordern","back_signin" to "Zurück zur Anmeldung","reset_screen" to "Anmeldeseite zurücksetzen","cloud_connected" to "● Cloud-Anmeldung verbunden","cloud_missing" to "● Cloud-Backend in diesem Build nicht konfiguriert","login_tip" to "Falsche Anmeldedaten werden automatisch gelöscht. Passwort-Wiederherstellung nutzt einen sicheren E-Mail-Link.","build_desc" to "Trainer-Konten · sichere QR-Einladungen · Passwort-Wiederherstellung · authentifizierte Cloud-Sitzungen."
    )
    val it=en+mapOf(
        "enter_email" to "Inserisci la tua e-mail.","enter_password" to "Inserisci la password.","checking" to "Controllo e-mail e password…","login_failed" to "Accesso non riuscito. Riprova o usa Password dimenticata.","reset_email_first" to "Inserisci prima l'e-mail del tuo account RS KICKBOXING.","sending_reset" to "Invio e-mail di recupero…","reset_sent" to "✓ Se questa e-mail appartiene a un account RS KICKBOXING, è stata inviata un'e-mail di recupero. Apri il link per tornare nell'app e scegliere una nuova password.","reset_failed" to "Impossibile richiedere il recupero.","new_password_min" to "Scegli una nuova password di almeno 10 caratteri.","passwords_no_match" to "Le due password non coincidono.","updating_password" to "Aggiornamento password…","password_updated" to "✓ Password aggiornata. Ora puoi accedere con la nuova password.","password_update_failed" to "Impossibile aggiornare la password. Apri prima il link di recupero ricevuto via e-mail.","activating" to "Attivazione account RS KICKBOXING…","account_signin_failed" to "Account creato, ma accesso non riuscito.","activate_failed" to "Impossibile attivare l'invito.","invite_loaded" to "Invito caricato. Scegli una password di almeno 10 caratteri.","recovery_title" to "Scegli una nuova password","forgot_title" to "Password dimenticata?","forgot_desc" to "Inserisci l'e-mail usata per il tuo account RS KICKBOXING. Invieremo un link sicuro per creare una nuova password.","recovery_desc" to "Il link di recupero ti ha riportato in RS KICKBOXING. Scegli la nuova password.","new_password" to "Nuova password (10+ caratteri)","create_password" to "Crea password (10+ caratteri)","confirm_password" to "Conferma nuova password","wait" to "Attendi…","save_new_password" to "Salva nuova password","send_reset" to "Invia e-mail di recupero","activate_account" to "Attiva account","sign_in" to "Accedi","forgot_button" to "Password dimenticata? Richiedine una nuova","back_signin" to "Torna al login","reset_screen" to "Reimposta schermata login","cloud_connected" to "● Login cloud collegato","cloud_missing" to "● Backend cloud non configurato in questa build","login_tip" to "I dati errati vengono cancellati automaticamente per un nuovo tentativo. Il recupero usa un link e-mail sicuro.","build_desc" to "Account creati dal trainer · inviti QR sicuri · recupero password · sessioni cloud autenticate."
    )
    val pl=en+mapOf(
        "enter_email" to "Wpisz e-mail.","enter_password" to "Wpisz hasło.","checking" to "Sprawdzanie e-maila i hasła…","login_failed" to "Logowanie nieudane. Spróbuj ponownie lub użyj opcji Nie pamiętam hasła.","reset_email_first" to "Najpierw wpisz e-mail konta RS KICKBOXING.","sending_reset" to "Wysyłanie e-maila resetującego…","reset_sent" to "✓ Jeśli ten e-mail należy do konta RS KICKBOXING, wysłano wiadomość resetującą. Otwórz link, wróć do aplikacji i ustaw nowe hasło.","reset_failed" to "Nie udało się poprosić o reset hasła.","new_password_min" to "Wybierz nowe hasło o długości co najmniej 10 znaków.","passwords_no_match" to "Hasła nie są takie same.","updating_password" to "Aktualizacja hasła…","password_updated" to "✓ Hasło zaktualizowane. Możesz zalogować się nowym hasłem.","password_update_failed" to "Nie udało się zaktualizować hasła. Najpierw otwórz link resetujący z e-maila.","activating" to "Aktywacja konta RS KICKBOXING…","account_signin_failed" to "Konto utworzone, ale logowanie nieudane.","activate_failed" to "Nie udało się aktywować zaproszenia.","invite_loaded" to "Zaproszenie wczytane. Wybierz hasło co najmniej 10-znakowe.","recovery_title" to "Wybierz nowe hasło","forgot_title" to "Nie pamiętasz hasła?","forgot_desc" to "Wpisz e-mail używany w koncie RS KICKBOXING. Wyślemy bezpieczny link do ustawienia nowego hasła.","recovery_desc" to "Link resetujący wrócił do RS KICKBOXING. Wybierz nowe hasło.","new_password" to "Nowe hasło (10+ znaków)","create_password" to "Utwórz hasło (10+ znaków)","confirm_password" to "Potwierdź nowe hasło","wait" to "Poczekaj…","save_new_password" to "Zapisz nowe hasło","send_reset" to "Wyślij e-mail resetujący","activate_account" to "Aktywuj konto","sign_in" to "Zaloguj","forgot_button" to "Nie pamiętasz hasła? Poproś o nowe","back_signin" to "Wróć do logowania","reset_screen" to "Zresetuj ekran logowania","cloud_connected" to "● Logowanie cloud połączone","cloud_missing" to "● Backend cloud nie jest skonfigurowany w tej wersji","login_tip" to "Błędne dane logowania są automatycznie czyszczone. Odzyskiwanie hasła używa bezpiecznego linku e-mail.","build_desc" to "Konta tworzone przez trenera · bezpieczne zaproszenia QR · odzyskiwanie hasła · uwierzytelnione sesje cloud."
    )
    val tr=en+mapOf(
        "enter_email" to "E-posta adresini gir.","enter_password" to "Şifreni gir.","checking" to "E-posta ve şifre kontrol ediliyor…","login_failed" to "Giriş başarısız. Tekrar dene veya Şifremi unuttum seçeneğini kullan.","reset_email_first" to "Önce RS KICKBOXING hesabının e-postasını gir.","sending_reset" to "Şifre sıfırlama e-postası gönderiliyor…","reset_sent" to "✓ Bu e-posta bir RS KICKBOXING hesabına aitse sıfırlama e-postası gönderildi. Uygulamaya dönmek ve yeni şifre seçmek için bağlantıyı aç.","reset_failed" to "Şifre sıfırlama isteği gönderilemedi.","new_password_min" to "En az 10 karakterli yeni bir şifre seç.","passwords_no_match" to "İki şifre eşleşmiyor.","updating_password" to "Şifre güncelleniyor…","password_updated" to "✓ Şifre güncellendi. Artık yeni şifrenle giriş yapabilirsin.","password_update_failed" to "Şifre güncellenemedi. Önce e-postadaki sıfırlama bağlantısını aç.","activating" to "RS KICKBOXING hesabın etkinleştiriliyor…","account_signin_failed" to "Hesap oluşturuldu ancak giriş başarısız.","activate_failed" to "Davet etkinleştirilemedi.","invite_loaded" to "Davet yüklendi. En az 10 karakterli bir şifre seç.","recovery_title" to "Yeni şifre seç","forgot_title" to "Şifreni mi unuttun?","forgot_desc" to "RS KICKBOXING hesabında kullandığın e-postayı gir. Yeni şifre oluşturman için güvenli bir bağlantı göndereceğiz.","recovery_desc" to "Sıfırlama bağlantısı seni RS KICKBOXING'a geri getirdi. Yeni şifreni seç.","new_password" to "Yeni şifre (10+ karakter)","create_password" to "Şifre oluştur (10+ karakter)","confirm_password" to "Yeni şifreyi onayla","wait" to "Lütfen bekle…","save_new_password" to "Yeni şifreyi kaydet","send_reset" to "Sıfırlama e-postası gönder","activate_account" to "Hesabı etkinleştir","sign_in" to "Giriş yap","forgot_button" to "Şifreni mi unuttun? Yeni şifre iste","back_signin" to "Girişe dön","reset_screen" to "Giriş ekranını sıfırla","cloud_connected" to "● Bulut girişi bağlı","cloud_missing" to "● Bulut backend bu sürümde yapılandırılmadı","login_tip" to "Yanlış giriş bilgileri yeni deneme için otomatik temizlenir. Şifre kurtarma güvenli e-posta bağlantısı kullanır.","build_desc" to "Antrenör tarafından oluşturulan hesaplar · güvenli QR davetleri · şifre kurtarma · kimliği doğrulanmış bulut oturumları."
    )
    val pack=when(lang.code){"nl"->nl;"pt"->pt;"es"->es;"fr"->fr;"de"->de;"it"->it;"pl"->pl;"tr"->tr;else->en}
    return pack[key]?:en[key]?:key
}
